### ISSUE TITLE
Use of PDF-DWG-Converter

### ISSUE THREAD

**Issue by AWEUZ** [dannyjanani/PDF-DWG-Converter#1]
Hi dannyjanani
What can I do if I want to use your code on my computer to convert files?

**Comment by dannyjanani** [comment]
Hi, 

I believe you need to run the fileListener executable, then the New PDFtoDWGConverter executable. I cannot verify this quickly since I no longer have windows and autoCAD. Let me know if it doesn't work and I'd be able to look into it more.

**Comment by dannyjanani** [comment]
https://www.dannyjanani.com/projects/pdf-dwg

I have a video at the link above of the project being used if that helps.
